# Generated by Django 3.0.4 on 2020-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_username', models.CharField(max_length=64)),
                ('from_username', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('timestamp_message', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
