# Generated by Django 3.0.4 on 2020-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_secret_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret_message',
            name='timestamp_message',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
