# Generated by Django 3.0.4 on 2020-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200406_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slambook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_username', models.CharField(max_length=64)),
                ('from_username', models.CharField(max_length=64)),
                ('no_saved', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('color_suits', models.CharField(max_length=128)),
                ('like', models.TextField(blank=True, null=True)),
                ('dislike', models.TextField(blank=True, null=True)),
                ('similar_things', models.TextField(blank=True, null=True)),
                ('sweet_memory', models.TextField(blank=True, null=True)),
                ('relation', models.CharField(max_length=64)),
                ('song', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('privacy', models.BooleanField(default=True)),
                ('share', models.CharField(max_length=64)),
                ('timestamp_slam', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
