# Generated by Django 3.0.4 on 2020-04-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200414_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='slambook',
            name='secret',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
