# Generated by Django 3.0.4 on 2020-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_slambook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='slambook',
            name='crush',
            field=models.TextField(default="I don't know"),
            preserve_default=False,
        ),
    ]
