# Generated by Django 3.0.4 on 2020-05-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_slambook_crush'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion_Email_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
